language: minimal
script: make
dist: bionic
addons:
  apt:
    packages:
    - emacs-nox
deploy:
  provider: pages:git
  edge: true
  keep_history: true
  deploy_key: ".deploy.key"
  repo: xdp-project/xdp-project.github.io
  target_branch: master
  local_dir: build/
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_f89b29d79295_key -iv $encrypted_f89b29d79295_iv
  -in .deploy.key.enc -out .deploy.key -d
